### ISSUE TITLE
I followed the instructions but error

### ISSUE THREAD

**Issue by Sys101-dot** [mikeale03/Sales-and-Inventory-System#40]
It says "Error accessing realm db" can you please put more instructions please. Thanks!

**Comment by mikeale03** [comment]
> It says "Error accessing realm db" can you please put more instructions please. Thanks!

just create a realm folder outside your project folder.

**Comment by Sys101-dot** [comment]
I tried creating outside the folder and inside sir both doesn't work(image1). However if i won't create my own project folder it works but it says error accessing realm db.(image2) 

I loved your projects but im having hard time on this one 

![image](https://github.com/mikeale03/Sales-and-Inventory-System/assets/173023347/639c4809-7b25-457e-9318-e099f5e92ea0)

![image](https://github.com/mikeale03/Sales-and-Inventory-System/assets/173023347/0dd8e7e4-4106-484a-943f-a18c22288ffa)

**Comment by Sys101-dot** [comment]
i'll try this one, appreciate your answer sir thanks hehe

**Comment by Sys101-dot** [comment]
It worked sir, thank you so much!
